spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://db_username:db_password@localhost:27017}
      database: pirullometro

youtube:
  api:
    base-url: https://www.googleapis.com
    key: ${YOUTUBE_API_KEY}
